### PR TITLE
Add isScanning method to determine whether the Lpf2Hub instance is still scanning or not

### PR DESCRIPTION
**Pull request by fredlcore**

### CODE REVIEW

**Comment by ThorstenBenter** [comment]
@fredlcore Bit late with my comment, but your changes are really helpful!!! My workaround for that was simply timing, but that is absolutely not elegant. Now the connection flow is super stable and the ESP never crashes anymore due to init issues.
Thank you very much!
Best
Thorsten

**Comment by fredlcore** [comment]
@ThorstenBenter: Thanks, I hope @corneliusmunz will agree and merge it into his repo...

**Comment by ThorstenBenter** [comment]
@fredlcore 

that would really be helpful! You may also want to add "isScanning	KEYWORD2" to the keywords.txt file; that changes the font color in the IDE, I believe. Goof for nothing other than knowing there was no typo ...
Best
Thorsten

**Review by corneliusmunz — APPROVED** [review]
@fredlcore many thanks for your contribution. I will change some small things after merging the PR (location of the function near to the other functions isConnecting... and additionally the addition of the function in the keywords file) but overall a great contribution 👍

**Comment by fredlcore** [comment]
You're more than welcome :) - thanks for working on this!

**Pull request merged**
